### PR TITLE
Issue 784 opt out learning tweet

### LINKED ISSUE #784: Hangout Learnings are Auto-Tweeted without Author's Knowledge or Consent
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
Hangout Learnings are auto-Tweeted without users knowledge or consent

What is the expected behavior?
Users should  be warned that Hangout Learnings are auto-Tweeted and can opt-out of that behavior

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #784

Checkbox is added in hangout and study group > Progress Log to permit user to opt-out sending tweets.

study_group_opt_out_tweet

hangout_opt_out_tweet

### CODE REVIEW

**Comment by nalbina** [comment]
really like that you have it checked by default :)

File: server/twitter/methods.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const tweetLearning = (learning)=>{
 
   if(Meteor.settings.isModeProduction){
 
-    const status = learning.title.truncate(250) + ' ~' + learning.username + ' #TodayILearned' ;
+    const status = learning.title.replace('@', ' ').truncate(250) + ' ~' + learning.username + ' #TodayILearned' ;
```
Comment (nalbina) [inline server/twitter/methods.js]: What is this line for?

Comment (railsstudent) [reply server/twitter/methods.js]: To avoid ppl to spam other twitter handlers in the learning tweet.
